
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Welcome to Leejaesoo’s Pages | ljs9643.github.io</title>
<meta name="generator" content="Jekyll v3.7.3" />
<meta property="og:title" content="Welcome to Leejaesoo’s Pages" />
<meta property="og:locale" content="en_US" />
<link rel="canonical" href="https://ljs9643.github.io/" />
<meta property="og:url" content="https://ljs9643.github.io/" />
<meta property="og:site_name" content="ljs9643.github.io" />
<script type="application/ld+json">
{"name":"ljs9643.github.io","@type":"WebSite","url":"https://ljs9643.github.io/","headline":"Welcome to Leejaesoo’s Pages","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <link rel="stylesheet" href="/assets/css/style.css?v=8c210c57d25321e3c457105019a87a5d6e19079a">
    <script src="https://code.jquery.com/jquery-3.3.0.min.js" integrity="sha256-RTQy8VOmNlT6b2PIRur37p6JEBZUE7o8wPgMvu18MC4=" crossorigin="anonymous"></script>
    <script src="/assets/js/main.js"></script>
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" integrity="sha256-3Jy/GbSLrg0o9y5Z5n1uw0qxZECH7C6OQpVBgNFYa0g=" crossorigin="anonymous"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  </head>
  <body>

      <header>
        <h1> </h1>
        <p></p>
      </header>

    <div class="wrapper">
      <nav>
        <ul></ul>
      </nav>
      <section>
<p> </p>


      </section>
    </div>

    
  </body>
</html>
